#ifndef TRANSFORMATION_PARAMS_H
#define TRANSFORMATION_PARAMS_H

// Include the coefficients generated by the Python script
const double transformation_coeffs[] = {
    // Add the coefficients here, for example:
    1.0, -2.0, 3.0, // Replace these with actual coefficients
};

const int num_coeffs = sizeof(transformation_coeffs) / sizeof(transformation_coeffs[0]);

#endif // TRANSFORMATION_PARAMS_H
